# Generated by Django 4.2.6 on 2023-10-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop_app", "0002_alter_category_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.CharField(default="", max_length=200),
        ),
    ]
