# Generated by Django 4.2.6 on 2023-10-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop_app", "0003_category_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
