# Generated by Django 2.2.14 on 2020-07-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20200706_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('on-review', 'On review'), ('approved', 'Approved'), ('published', 'Published')], default='published', max_length=9),
        ),
    ]
