"""add deleted column to Product model

Revision ID: 00f70cd3ea9a
Revises: f9c0e1ccb734
Create Date: 2020-12-07 21:00:26.231580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00f70cd3ea9a'
down_revision = 'f9c0e1ccb734'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('deleted', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'deleted')
    # ### end Alembic commands ###
