# Generated by Django 2.2.12 on 2020-04-13 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('text', models.TextField()),
                ('time_to_read', models.IntegerField(choices=[(1, '< 1 min'), (2, '1-5 min'), (3, '5-15 min'), (4, '15-30 min'), (5, '> 30 min')])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myblog.Author')),
            ],
        ),
    ]
