# Generated by Django 2.2.12 on 2020-04-13 16:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ts_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='ts_last_changed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
