# Generated by Django 2.2.11 on 2020-03-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factoriesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='nick', max_length=30),
            preserve_default=False,
        ),
    ]
