# Generated by Django 2.2.11 on 2020-03-05 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factoriesapp', '0003_auto_20200305_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipped_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='factoriesapp.Employee'),
        ),
    ]
