# Generated by Django 3.2.3 on 2021-05-31 17:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=2)),
                ('username', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=250)),
                ('birth_dt', models.DateField()),
                ('birth_month', models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myfactoriesapp.group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
