# Generated by Django 2.2.1 on 2019-05-27 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexpage', '0002_article_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='likes',
        ),
    ]
