# Generated by Django 2.2.14 on 2020-07-20 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=2)),
                ('username', models.CharField(max_length=64)),
                ('nickname', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('birth_date', models.DateField()),
                ('birth_month', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='factoriesapp.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
