# Generated by Django 2.2.14 on 2020-07-20 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factoriesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='factoriesapp.User')),
                ('internal_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('factoriesapp.user',),
        ),
    ]
