# Generated by Django 4.2.4 on 2023-12-14 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_animal_create_animal_update_food_create_food_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAnimal',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.animal')),
                ('last_owner_name', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('mainapp.animal',),
        ),
        migrations.CreateModel(
            name='WildAnimal',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.animal')),
            ],
            options={
                'abstract': False,
            },
            bases=('mainapp.animal',),
        ),
    ]
