# Generated by Django 4.2.4 on 2023-12-14 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_homeanimal_wildanimal'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.animal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
