FROM python:3.8.5

WORKDIR /app


COPY requirements.txt ./

RUN pip install -r requirements.txt

COPY . .

RUN chmod +x entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]
CMD ["python", "app.py"]

EXPOSE 5000
