"""Add 'is_new' col on Product model

Revision ID: bc078338e36f
Revises: 111ba31234cd
Create Date: 2021-05-06 19:56:48.233186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc078338e36f'
down_revision = '111ba31234cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('is_new', sa.Boolean(), server_default='FALSE', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'is_new')
    # ### end Alembic commands ###
