# Generated by Django 2.2.12 on 2020-04-18 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfactoriesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=2)),
                ('username', models.CharField(max_length=40)),
                ('nickname', models.CharField(max_length=40)),
                ('birth_dt', models.DateField()),
                ('birth_month', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myfactoriesapp.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
