# Generated by Django 2.2.12 on 2020-04-18 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfactoriesapp', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myfactoriesapp.User')),
                ('internal_id', models.IntegerField()),
                ('internal_email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
            bases=('myfactoriesapp.user',),
        ),
    ]
