# Generated by Django 2.2.12 on 2020-04-18 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfactoriesapp', '0003_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('awaiting_shipment', 'Awaiting Shipment'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], max_length=30)),
                ('shipped_on', models.DateTimeField(null=True)),
                ('delivered_on', models.DateTimeField(null=True)),
                ('shipped_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myfactoriesapp.Employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
