"""empty message

Revision ID: 0058c547772d
Revises: 9a189cd210c4
Create Date: 2023-11-30 18:00:01.959052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0058c547772d'
down_revision = '9a189cd210c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
