"""add column created_at to products table

Revision ID: c8365fe7151d
Revises: 556a762ef846
Create Date: 2021-11-25 20:41:28.846781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8365fe7151d'
down_revision = '556a762ef846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'created_at')
    # ### end Alembic commands ###
