# Generated by Django 3.2 on 2021-12-09 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_alter_article_published_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='VipAuthor',
            fields=[
                ('author_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posting.author')),
                ('super_degree', models.PositiveSmallIntegerField(default=1)),
            ],
            bases=('posting.author',),
        ),
    ]
