# Generated by Django 3.2 on 2021-12-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0008_auto_20211213_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(related_name='articles', to='posting.ArticleTag'),
        ),
    ]
