# Generated by Django 3.2 on 2021-12-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0009_alter_article_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='read_qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
