# Generated by Django 5.0 on 2023-12-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_animal_create_duplicated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='a',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='animal',
            name='b',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='animal',
            name='d',
            field=models.IntegerField(default=2),
        ),
    ]
