# Generated by Django 2.2.4 on 2019-08-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20190829_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='comment',
            field=models.CharField(default='', max_length=250),
        ),
    ]
