# Generated by Django 2.2.9 on 2020-01-23 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('otusblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
