# Generated by Django 2.2.9 on 2020-01-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otusblog', '0003_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.IntegerField(choices=[(1, 'News'), (2, 'Announcements')], default=1),
            preserve_default=False,
        ),
    ]
