"""add column is_new to products table

Revision ID: 6b774b18b453
Revises: c8365fe7151d
Create Date: 2021-11-25 21:11:31.970508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b774b18b453'
down_revision = 'c8365fe7151d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('is_new', sa.Boolean(), server_default='FALSE', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'is_new')
    # ### end Alembic commands ###
