"""add column is_new to products table

Revision ID: 83c36e8a0016
Revises: f9b746ce7dde
Create Date: 2022-04-28 21:03:06.092380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83c36e8a0016'
down_revision = 'f9b746ce7dde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('is_new', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'is_new')
    # ### end Alembic commands ###
