# Generated by Django 3.2 on 2021-12-09 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0004_shorttitlearticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('text', models.TextField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posting.author')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
